# Generated by Django 5.2 on 2025-04-09 01:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pessoa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('telefone', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('cpf', models.CharField(max_length=14, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Plano',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('descricao', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ServicoProduto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('descricao', models.TextField(blank=True, null=True)),
                ('valor', models.DecimalField(decimal_places=2, max_digits=10)),
                ('eh_produto', models.BooleanField(default=False, verbose_name='É Produto?')),
            ],
            options={
                'verbose_name': 'Serviço ou Produto',
                'verbose_name_plural': 'Serviços e Produtos',
            },
        ),
        migrations.CreateModel(
            name='Grupo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('pessoas', models.ManyToManyField(blank=True, related_name='grupos', to='core.pessoa')),
                ('planos', models.ManyToManyField(blank=True, related_name='grupos', to='core.plano')),
            ],
        ),
        migrations.CreateModel(
            name='PlanoServico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('desconto', models.DecimalField(decimal_places=2, help_text='Percentual de desconto para o serviço neste plano', max_digits=5)),
                ('plano', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plano_servicos', to='core.plano')),
                ('servico', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plano_servicos', to='core.servicoproduto')),
            ],
            options={
                'unique_together': {('plano', 'servico')},
            },
        ),
    ]
